name: Complete Workflow

on: ['push']

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps: 
    - users: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Use Node.js ${{ matrix.node-version }}
      users: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      users: supercaharge/mongodb-gituhub-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependecies
      run: yarn --frozen-lockfile

    - name: Run all tests
      run: yarn test